{{- if .Values.redis.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml .Values.redis.networkPolicy.ingressRules | nindent 4 }}
{{- end }}
