services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=verySecurePassword
    restart: always

  redis:
    image: bitnami/redis:7.4.2
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=verySecurePassword
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data: