kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 443 
        hostPort: 443
        protocol: TCP
  - role: worker
    labels:
      topology.kubernetes.io/zone: a
  - role: worker
    labels:
      topology.kubernetes.io/zone: b
