{{- if .Values.webapp.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "webapp.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.webapp.networkPolicy.ingressRules | nindent 4 }}
  egress:
    {{- toYaml .Values.webapp.networkPolicy.egressRules | nindent 4 }}
{{- end }}
